name: Teste unitário de Backend

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

concurrency:
  group: ci-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Cache backend node_modules
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: backend-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            backend-node-

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Make envfile
        working-directory: ./backend
        uses: SpicyPizza/create-envfile@v1        
        with:
          envkey_DEBUG: false
          envkey_DATABASE_URL: "file:./dev.db"          
          file_name: .env

      - name: Generate Prisma Client
        working-directory: ./backend
        run: npx prisma generate

      - name: Run backend unit tests
        working-directory: ./backend
        run: npm run test -- --runInBand
        env:
          CI: true